import type { Config } from 'tailwindcss';
const config: Config = {
  darkMode: ['class'],
  content: ['./pages/**/*.{ts,tsx}', './components/**/*.{ts,tsx}', './app/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: { DEFAULT: 'hsl(var(--primary))', foreground: 'hsl(var(--primary-foreground))' },
        secondary: { DEFAULT: 'hsl(var(--secondary))', foreground: 'hsl(var(--secondary-foreground))' },
        muted: { DEFAULT: 'hsl(var(--muted))', foreground: 'hsl(var(--muted-foreground))' },
        accent: { DEFAULT: 'hsl(var(--accent))', foreground: 'hsl(var(--accent-foreground))' },
        destructive: { DEFAULT: 'hsl(var(--destructive))', foreground: 'hsl(var(--destructive-foreground))' },
        card: { DEFAULT: 'hsl(var(--card))', foreground: 'hsl(var(--card-foreground))' },
        popover: { DEFAULT: 'hsl(var(--popover))', foreground: 'hsl(var(--popover-foreground))' },
      },
      borderRadius: { lg: 'var(--radius)', md: 'calc(var(--radius) - 2px)', sm: 'calc(var(--radius) - 4px)' },
      keyframes: {
        'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up': { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
        shimmer: { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        float: { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-12px)' } },
        blob: { '0%,100%': { borderRadius: '60% 40% 30% 70% / 60% 30% 70% 40%' }, '50%': { borderRadius: '30% 60% 70% 40% / 50% 60% 30% 60%' } },
        'spin-slow': { to: { transform: 'rotate(360deg)' } },
        'gradient-x': { '0%,100%': { backgroundPosition: '0% 50%' }, '50%': { backgroundPosition: '100% 50%' } },
        'slide-up': { from: { opacity: '0', transform: 'translateY(30px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        'slide-in-right': { from: { opacity: '0', transform: 'translateX(30px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
        'scale-up': { from: { opacity: '0', transform: 'scale(0.9)' }, to: { opacity: '1', transform: 'scale(1)' } },
        'fade-in': { from: { opacity: '0' }, to: { opacity: '1' } },
        'pulse-glow': { '0%,100%': { boxShadow: '0 0 20px rgba(251,146,60,0.4)' }, '50%': { boxShadow: '0 0 40px rgba(251,146,60,0.8), 0 0 80px rgba(251,146,60,0.3)' } },
        'border-flow': { '0%': { backgroundPosition: '0% 50%' }, '100%': { backgroundPosition: '200% 50%' } },
        'typewriter': { from: { width: '0' }, to: { width: '100%' } },
        marquee: { '0%': { transform: 'translateX(0)' }, '100%': { transform: 'translateX(-50%)' } },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        shimmer: 'shimmer 2.5s linear infinite',
        float: 'float 4s ease-in-out infinite',
        blob: 'blob 8s ease-in-out infinite',
        'spin-slow': 'spin-slow 12s linear infinite',
        'gradient-x': 'gradient-x 4s ease infinite',
        'slide-up': 'slide-up 0.7s cubic-bezier(0.16,1,0.3,1) forwards',
        'slide-in-right': 'slide-in-right 0.7s cubic-bezier(0.16,1,0.3,1) forwards',
        'scale-up': 'scale-up 0.5s cubic-bezier(0.16,1,0.3,1) forwards',
        'fade-in': 'fade-in 0.6s ease forwards',
        'pulse-glow': 'pulse-glow 2s ease-in-out infinite',
        'border-flow': 'border-flow 3s linear infinite',
        marquee: 'marquee 20s linear infinite',
      },
      backgroundSize: { '300%': '300%' },
      fontFamily: { arabic: ['Tajawal', 'sans-serif'] },
      boxShadow: {
        'glow-sm': '0 0 15px rgba(251,146,60,0.25)',
        'glow': '0 0 30px rgba(251,146,60,0.35)',
        'glow-lg': '0 0 60px rgba(251,146,60,0.45)',
        'glow-xl': '0 0 100px rgba(251,146,60,0.3)',
        'inner-glow': 'inset 0 1px 0 rgba(255,255,255,0.1), inset 0 -1px 0 rgba(0,0,0,0.1)',
        'card': '0 1px 3px rgba(0,0,0,0.05), 0 0 0 1px rgba(0,0,0,0.03)',
        'card-hover': '0 20px 60px rgba(0,0,0,0.1), 0 0 0 1px rgba(251,146,60,0.15)',
        'premium': '0 4px 20px rgba(251,146,60,0.3), 0 1px 3px rgba(0,0,0,0.1)',
        'premium-hover': '0 8px 40px rgba(251,146,60,0.5), 0 2px 8px rgba(0,0,0,0.1)',
        'dark': '0 8px 32px rgba(0,0,0,0.3)',
        'dark-lg': '0 20px 60px rgba(0,0,0,0.4)',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
export default config;
